#ifndef _JMP_CONFIG_H
#define _JMP_CONFIG_H


#define COMMAND_EXECUTION_PARAM_SUM				16


#define GCODE_BUFF_SUM									2048
#define GCODE_LINE_BUFF_SUM							100
#define GCODE_PARAM_SUM									16
#define GCODE_PARAM_LENGTH							20


#define STORAGE_READ_FILE_PATH_SUM				100
#define STORAGE_READ_BUFF_SUM							100

#define PARAM_STATE_AXIS_SUM						4
#define PARAM_STATE_LEVELIING_POINT_MAX	5


#define GUI_UART_RX_BUFF_SUM							1024
#define GUI_UART_TX_BUFF_SUM							1024

#define GUI_UARTSTRUCT_DATA_SUM						1024

#define GUI_GCODE_FILE_NAME_LEN						100
#define GUI_GCODE_FILE_SUM								128





#endif


